= Overview
There will be another pandemic. There will be another earthquake. There will be another tsunami. There will be another meteor impact. There will be another disaster.
Why not start a worldwide consortium of skilled analysts to anticipate the future disasters and make plans for dealing with them?
We were reasonbly but certainly not sufficiently prepared for the Wuhanvirus Pandemic. Many problems emerged. 
One of those problems was the political opportunism of our leaders to advance their own ideological agendas while everyone else was distracted. Another problem was profiteering and exploiting the temporary weakness of others to make them permanently weaker.
The pandemic is understood at the levels of biology, morality, cultural and social change and rational response.

I'm trying to figure out how to get people to put some new laws in place for the next pandemic or national emergency.
We know there is going to be one.
It might not be global but something is always going wrong somewhere.
The idea I am trying to work out is how to treat shutting down a city or state or country like shutting off a computer (don't worry ... I won't use this analogy) ...
Shutting down a computer is a set of very ordering steps which store needed information for the reboot which is presumed to come.
Naturally if the shutdown is the result of serious damage the restoration information will still be useful but for the reconstruction period.
The unlocking of society we see today is the same as a reboot.
We need to have protocols for what to shut down and how and for how long and then what to restart and when.

Questions like "compensation" for lost work and "essential" versus "non-essential" services need to be formalised.

We also need to put these in place to make sure the police and elected officials do not exceed their authority or use the opportunity to ram through highly undesirable social legislation (e.g.Trudeau banning all kinds of guns because the Parliament is not in session and he just gets to do it) by making any "orders in cabinet" during this period *automatically* go away once the emergency is over.

No country's "emergency measures" specify the process in detail.

The Navy has very carefully specified procedures for "mothballing" an aircraft carrier, for maintaining it while in mothballs, and for "restoring" a mothballed ship to active service.

A nation and its various institutions and economy is arguably more complicated than an aircraft carrier.

National "Emergency Powers" legislation is a few paragraphs long at most.
I can't even begin to imagine what the "How To Mothball an Aircraft Carrier" manual looks like.

The police also need protection from being given "illegitimate" rules by politicians. Vagueness allows politicians to invent interpretations (e.g. the governor of Michigan banning the sale of flower seeds) and the police are compelled to enforce these rules. This situation brings the police into conflict with society and erodes public confidence. This damage lasts a long time.

What can be done?
The best single option might be to take advantage of the enormous talent in simulation modelling and gaming which is out there as well as the idea of creating a collaboration to come up with scenarios and options for future lockdowns and unlockings. 

Simulation models for Weather, Climate, Urban Planning, and the Civilisation series all have the nuances and power to run many scenarios.
Military schools are forever refighting old battles and imagining new ones.
The first phase of this crowd-sourced and open-sourced project could be just to decide what it was supposed to be doing.

